# Generated by Django 5.1.7 on 2025-05-04 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='refeicao',
            name='alimentos',
            field=models.ManyToManyField(blank=True, related_name='refeicoes', to='main_app.alimento'),
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='main_app.alimento')),
                ('substituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='main_app.alimento')),
            ],
        ),
    ]
