# Generated by Django 5.1.7 on 2025-05-04 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alimento_refeicao_alimentos_substituicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicao',
            name='alimentos',
        ),
        migrations.RemoveField(
            model_name='substituicao',
            name='substituto',
        ),
        migrations.AddField(
            model_name='alimento',
            name='quantidade',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='alimento',
            name='refeicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='main_app.refeicao'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='unidade',
            field=models.CharField(default='g', max_length=50),
        ),
        migrations.AddField(
            model_name='substituicao',
            name='opcao',
            field=models.CharField(default='Substituto', max_length=100),
        ),
        migrations.AddField(
            model_name='substituicao',
            name='quantidade',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='substituicao',
            name='unidade',
            field=models.CharField(default='g', max_length=50),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nome',
            field=models.CharField(default='Alimento', max_length=100),
        ),
        migrations.AlterField(
            model_name='substituicao',
            name='alimento_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitutos', to='main_app.alimento'),
        ),
    ]
